### PR TITLE
Added support qt install framework for Windows and Linux

### PR DESCRIPTION
**Pull request by EndrII**
Hey. I saw your application in SnapStore. I liked it very much, thank you for that.
I want to offer you installer support for Windows and Linux.

## Appearance :
Screenshot from 2020-03-27 11-04-33

It will look approximately the same in Windows.

Deployment:
* Install cqtdeployer from [SnapStore](https://snapcraft.io/cqtdeployer) or [github releases](https://github.com/QuasarApp/CQtDeployer/releases)
* build you application on release mode.
* and run cqtdeployer on root dir of your application.
```
cd BingWall
cqtdeployer
```
if you use cqtdeployer from snapstore, please add it all permissions.
After deploy check DistributionKit folder.

---
CQtDeployer github [page](https://github.com/QuasarApp/CQtDeployer).

### CODE REVIEW

**Comment by keshavbhatt** [comment]
I will checkout the PR soon, 
Currently the app only able to change wallpaper on gnome desktop. Making a windows installer will make sense when we will have option to chnage wallpaper on windows too.

Am not aware of cqtdeplyer yet, and don't know how it works on Linux systems. After understanding all this and reviewing the changes you proposed i would be able to merge the PR. 

Thanks

**Comment by EndrII** [comment]
ok, I will wait for your decision.

**Comment by keshavbhatt** [comment]
I tried your instructions and nothing happened, could you please elaborate how to proceed ??

**Comment by EndrII** [comment]
strange, can i get the cqtdeployer logs?

**Comment by keshavbhatt** [comment]
> strange, can i get the cqtdeployer logs?

I downloaded the your repo with updated code for bingwall, build bingwall in the release folder when i run cqtdeployer nothing happens, shows me optionsonly.

**Comment by EndrII** [comment]
cqtdeployer needs to be run not in the release folder but in the folder with CQDeployer.json

Run please cqtdeployer in the root folder of your project. like a snapcraft.
find the CQDeployer.json and open this contains it folder on console and run cqtdeployer.

If CQtDeployer still displays help, make sure it has all the permissions that it needs.

**Comment by keshavbhatt** [comment]
okay i will do it.

**Comment by EndrII** [comment]
works?

**Comment by keshavbhatt** [comment]
Oh, sorry i was running it in /tmp dir where snap of cqtdeployer cannot see.
I copied the directory to ~/ and it agev me the following output:
```
cqtdeployer 
Info: Deploy ...
Info: flag targetDir not  used. use default target dir :/home/bulld/kk/BingWall/DistributionKit
Error: The deployment target requir Qt libs, but init qmake is failed.
Error: deploy is failed!
```

**Comment by EndrII** [comment]
do you added all permissions for cqtdeployer?. Apparently, cqtdeployer cannot ask qmake about qt environment or qmake is in a place where snap cannot get access.

**Comment by EndrII** [comment]
image

**Comment by EndrII** [comment]
if you use qmake from Linux repository then do not use snap. becouse snap have own root file system. 
remove cqtdeployer of snap and install qif version of cqtdeployer from [download page](https://github.com/QuasarApp/CQtDeployer/releases/download/1.4.1/LinuxInstaller.run). and try again.

**Comment by keshavbhatt** [comment]
> do you added all permissions for cqtdeployer?

I have all permissions turned on, i will download the local installer and try again. 
But you know you can request classic confinement for your snap in snap store describing a valid reason.

**Comment by EndrII** [comment]
yes, i know it, but in my case, it would be enough for me to get the opportunity to only read the root file system of the parent OS, the classic mode is not safe.

**Comment by EndrII** [comment]
the cqtdeployer tool are updated, try deploy your application now

**Comment by EndrII** [comment]
No reactions of maintainers ...

**Pull request closed without merging**
