### PR TITLE
Sorting downloaded wallpapers

### PR DESCRIPTION
**Pull request by devesh525s**
Downloaded wallpapers would now be shown in recent-first order

### CODE REVIEW

**Comment by keshavbhatt** [comment]
Thank you @devesh525s for this PR :)

I tested it and it works as expected. 

The other way to do it would be using QDir's sorting flags. In that case we would define our files object like this and get similar result (this flag Sorts content of dir by time (modification time)). 

`  QFileInfoList files = dir.entryInfoList(filter, QDir::Files, QDir::Time);
`

Let's do it in this way, what you say?

**Comment by keshavbhatt** [comment]
If you want your can modify your PR and we will merge it.

**Comment by devesh525s** [comment]
Oh, I thought you wanted to do it yourself. Updated the PR. Do check :)

**Review by keshavbhatt — APPROVED** [review]

**Comment by devesh525s** [comment]
Looks good :)

**Pull request merged**
